CREATE TABLE "meteo"."current_weather" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "date" timestamp(6) NOT NULL,
  "weather_id" int2,
  "weather_main" varchar(50) COLLATE "pg_catalog"."default",
  "weather_description" varchar(50) COLLATE "pg_catalog"."default",
  "weather_icon" varchar(10) COLLATE "pg_catalog"."default",
  "current_temp" numeric(6,2),
  "current_feels_like" numeric(6,2),
  "current_pressure" numeric(6,2),
  "current_humidity" numeric(6,2),
  "current_visibility" int2,
  "current_wind_speed" numeric(6,2),
  "current_wind_deg" numeric(6,2),
  "current_clouds" numeric(6,2),
  "current_rain_1h" numeric(6,2),
  "current_snow_1h" numeric(6,2),
  "current_sunrise" timestamp(6),
  "current_sunset" timestamp(6),
  "current_uvi" numeric(6,2),
  "current_dew_point" numeric(6,2),
  "current_wind_gust" numeric(6,2),
  CONSTRAINT "current_weather_pkey" PRIMARY KEY ("id")
)
;
ALTER TABLE "meteo"."current_weather" 
  OWNER TO "postgres";

CREATE INDEX "current_weather_date_idx" ON "meteo"."current_weather" USING btree (
  "date" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);

COMMENT ON COLUMN "meteo"."current_weather"."date" IS 'дата измерений';
COMMENT ON COLUMN "meteo"."current_weather"."weather_id" IS 'Идентификатор погодных условий';
COMMENT ON COLUMN "meteo"."current_weather"."weather_main" IS 'Группа погодных параметров (Дождь, Снег, Экстрим и др.)';
COMMENT ON COLUMN "meteo"."current_weather"."weather_description" IS 'Погодные условия в группе на своем языке';
COMMENT ON COLUMN "meteo"."current_weather"."weather_icon" IS 'Идентификатор значка погоды';
COMMENT ON COLUMN "meteo"."current_weather"."current_temp" IS 'Температура';
COMMENT ON COLUMN "meteo"."current_weather"."current_feels_like" IS 'как ощущается';
COMMENT ON COLUMN "meteo"."current_weather"."current_pressure" IS 'Атмосферное давление, гПа';
COMMENT ON COLUMN "meteo"."current_weather"."current_humidity" IS 'Влажность,%';
COMMENT ON COLUMN "meteo"."current_weather"."current_visibility" IS 'видимость';
COMMENT ON COLUMN "meteo"."current_weather"."current_wind_speed" IS 'Скорость ветра, метр / сек';
COMMENT ON COLUMN "meteo"."current_weather"."current_wind_deg" IS 'Направление ветра, градусы';
COMMENT ON COLUMN "meteo"."current_weather"."current_clouds" IS 'Облачность,%';
COMMENT ON COLUMN "meteo"."current_weather"."current_rain_1h" IS 'Объем дождя за последний час, мм';
COMMENT ON COLUMN "meteo"."current_weather"."current_snow_1h" IS 'Объем снега за 1 час, мм';
COMMENT ON COLUMN "meteo"."current_weather"."current_sunrise" IS 'Время восхода, unix, UTC';
COMMENT ON COLUMN "meteo"."current_weather"."current_sunset" IS 'Время заката, unix, UTC';
COMMENT ON COLUMN "meteo"."current_weather"."current_uvi" IS 'Текущий УФ-индекс';
COMMENT ON COLUMN "meteo"."current_weather"."current_dew_point" IS 'Атмосферная температура (меняется в зависимости от давления и влажности), ниже которой капли воды начинают конденсироваться и может образовываться роса';
COMMENT ON COLUMN "meteo"."current_weather"."current_wind_gust" IS 'Порыв ветра. Единицы - по умолчанию: метр / сек, метрическая система: метр / сек, британская: мили / час.';
