CREATE TABLE "meteo"."forecast_hourly" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "date" timestamp(6) NOT NULL,
  "hourly_temp" numeric(6,2),
  "hourly_feels_like" numeric(6,2),
  "hourly_pressure" numeric(6,2),
  "hourly_humidity" numeric(6,2),
  "hourly_dew_point" numeric(6,2),
  "hourly_uvi" numeric(6,2),
  "hourly_clouds" numeric(6,2),
  "hourly_visibility" int2,
  "hourly_wind_speed" numeric(6,2),
  "hourly_wind_gust" numeric(6,2),
  "hourly_wind_deg" numeric(6,2),
  "hourly_pop" numeric(6,2),
  "hourly_rain_1h" numeric(6,2),
  "hourly_snow_1h" numeric(6,2),
  "weather_id" int2,
  "weather_main" varchar(50) COLLATE "pg_catalog"."default",
  "weather_description" varchar(50) COLLATE "pg_catalog"."default",
  "weather_icon" varchar(10) COLLATE "pg_catalog"."default",
  CONSTRAINT "forecast_hourly_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "meteo"."forecast_hourly" 
  OWNER TO "postgres";

COMMENT ON COLUMN "meteo"."forecast_hourly"."id" IS 'Идентификатор';
COMMENT ON COLUMN "meteo"."forecast_hourly"."date" IS 'дата измерений';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_temp" IS 'Температура. Units – default: kelvin, metric: Celsius, imperial: Fahrenheit.';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_feels_like" IS 'Температура. Человеческое восприятие погоды, ощущается как. Units – default: kelvin, metric: Celsius, imperial: Fahrenheit. ';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_pressure" IS 'Атмосферное давление на уровне моря, hPa';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_humidity" IS 'Влажность, %';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_dew_point" IS 'Атмосферная температура (изменяющаяся в зависимости от давления и влажности), ниже которой капли воды начинают конденсироваться и может образовываться роса. Units – default: kelvin, metric: Celsius, imperial: Fahrenheit';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_uvi" IS 'УФ-индекс';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_clouds" IS 'Облачность, %';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_visibility" IS 'Средняя видимость, metres';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_wind_speed" IS 'Скорость ветра. Units – default: metre/sec, metric: metre/sec, imperial: miles/hour';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_wind_gust" IS 'Порывы ветра. Units – default: metre/sec, metric: metre/sec, imperial: miles/hour.';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_wind_deg" IS 'Направление ветра, градусы';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_pop" IS 'Вероятность осадков';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_rain_1h" IS 'Объем осадков - дождя за прошлый час, mm';
COMMENT ON COLUMN "meteo"."forecast_hourly"."hourly_snow_1h" IS 'Объем осадков - снега за прошлый час, mm';
COMMENT ON COLUMN "meteo"."forecast_hourly"."weather_id" IS 'Идентификатор погодных условий';
COMMENT ON COLUMN "meteo"."forecast_hourly"."weather_main" IS 'Группа погодных условий (Rain, Snow, Extreme etc.)';
COMMENT ON COLUMN "meteo"."forecast_hourly"."weather_description" IS 'Погодные условия внутри группы (Дождь - Легкий дождь)';
COMMENT ON COLUMN "meteo"."forecast_hourly"."weather_icon" IS 'Идентификатор иконки погоды';
