CREATE TABLE "meteo"."wind_deg" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "wind_deg_from" int4,
  "wind_deg_to" int4,
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "full_name" varchar(255) COLLATE "pg_catalog"."default",
  "order_num" int4,
  CONSTRAINT "wind_deg_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "meteo"."wind_deg" 
  OWNER TO "postgres";

COMMENT ON COLUMN "meteo"."wind_deg"."wind_deg_from" IS 'Градус-начало сектора';
COMMENT ON COLUMN "meteo"."wind_deg"."wind_deg_to" IS 'Градус-окончание сектора';
COMMENT ON COLUMN "meteo"."wind_deg"."name" IS 'Наименование направления ветра';
COMMENT ON COLUMN "meteo"."wind_deg"."full_name" IS 'Полное наименование направления ветра';
COMMENT ON COLUMN "meteo"."wind_deg"."order_num" IS '№ п/п';
